name: 'Read version in package.json'
description: 'Output version numbers with package.json'
branding:
  icon: package
  color: 'blue'
inputs:
  path:
    description: 'Path of package.json'
    default: "./"
outputs:
  version:
    description: "Version of package"
runs:
  using: 'node20'
  main: 'lib/index.js'
